spring:
  application:
  name: yourDost
  datasource:
    url: jdbc:postgresql://localhost:5432/employee
    username: shekharbhardwaj
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true